src/content.config.ts
src/content/events/ios-dev-scout/april-2025/index.md
src/content/events/juniordevsg/coding-dojo-april2025/index.md
src/layouts/BlogPost.astro

If `rsvpButtonUrl` is specified, a button will appear below the title. The label defaults to "Link", or can be configured via `rsvpButtonText`.

Add RSVP button to event page

---

astro.config.mjs
src/components/BaseHead.astro
src/content/events/ios-dev-scout/april-2025/index.md
src/content/events/juniordevsg/coding-dojo-april2025/index.md
src/layouts/EventPost.astro
src/pages/about.astro
src/pages/events/[...slug].astro

- OG image
- Update OG descriptions for events.

Update OG header stuff

---

src/layouts/OrgPage.astro
src/pages/about.astro

.. and also remove some unused styles from OrgPage.
This also fixes `npm run build`, since we did not supply some required parameters. For better DevEx, it might be worth looking into catching this from linting rather than at build time, but that's for another PR.

Use OrgPage layout for About

---

src/components/BaseHead.astro

- Attempt to use PNG format instead.

Use getImage to reformat the image.

---

.vscode/settings.json
package-lock.json
package.json
src/components/BaseHead.astro
src/styles/GlobalStyles.astro

Setup GlobalStyles.astro for global styles.
Update font family for header and normal text.

Setup global styles

---

src/components/Header.astro

Turn the nav bar into a hamburger menu below the 720px breakpoint.

style: hamburger menu for mobile view

---

src/components/BaseHead.astro

- Strange issue that overwrote `<title>` tag.

Fix: Fix header

---

src/pages/events/index.astro
src/styles/GlobalStyles.astro

- Define more text utility classes
- Define gray styles
- Define margin and padding utility classes
- Create .tag-list and .tag global classes
- Display tags in event card on event listing page
- Update style for event card on event listing page

Update global styles and event listing page

---

astro.config.mjs
package-lock.json
package.json
src/components/AddToCalendarButton.tsx
src/components/SummaryCard.astro
src/layouts/EventPost.astro
tsconfig.json

- Summary card
- Add to Calendar widget

New Summary Card component and added to event page

---

src/content.config.ts
src/content/orgs/juniordevsg/index.md
src/layouts/OrgPage.astro

- Display a list of links for orgs to share.

Feat: Show list of links for Orgs

---

src/components/Footer.astro
src/components/Header.astro
src/consts.ts
src/layouts/OrgPage.astro
src/layouts/Theme.astro
src/pages/events/index.astro
src/pages/orgs/index.astro
src/styles/GlobalStyles.astro
src/styles/fontawesome/scss/_variables.scss

- Create colorful theme
- Create Theme.astro layout component
- Define DEFAULT_THEME in consts.ts
- Update all pages, except event post page with new theme
- Fixed fontawesome base path for font files

Create colorful theme

---

docs/org_template.md
src/content.config.ts
src/content/orgs/division_zero_div0/index.md
src/content/orgs/hackware/index.md
src/content/orgs/ios-dev-scout/index.md
src/content/orgs/juniordevsg/index.md
src/content/orgs/women_devs_sg/index.md
src/layouts/OrgPage.astro

- Update styling of org profile page
- Add logo
- Add tags
- Add social links

Update organisation profile page

---

src/pages/orgs/index.astro
src/pages/orgs/search-index.json.ts
src/styles/GlobalStyles.astro

Generate search index for orgs collection and implement simple search for org list page.

Search for org list page

---

src/content/orgs/juniordevsg/index.md
src/layouts/EventPost.astro
src/layouts/OrgPage.astro
src/pages/orgs/index.astro

- Link to org profile from event page
- Update styling for org logos
- Also added logo for jdsg

Link to org profile from event page, update styling for org logos

---

src/layouts/OrgPage.astro
src/pages/events/index.astro
src/pages/orgs/[...slug].astro
src/styles/GlobalStyles.astro

feat(#50): Show upcoming and past events on organisation profile page

---

src/content/events/lorong-ai/2025-05-06-ai-tools-days/index.md
src/content/orgs/lorong-ai/index.md

- Ensure that Lorong AI Org and past events are in the correct format.

Fix: Update Lorong AI front-matter to the correct format.

---

src/pages/events/index.astro
src/pages/events/search-index.json.ts
src/pages/rss.xml.js

- Display upcoming events instead of all events.

Use upcoming events

---

src/content/events/tech_leadership_circle/workshop_system_design/index.md

Updated the event to the new date

Update system design workshop date

---

.github/workflows/google-form-webhook.yml
docs/webhook.http

Experiment with Google Form to trigger webhook.

feature: Add workflow to be triggered with Webhook.

---

.github/workflows/event-scrapper.yml
.github/workflows/google-form-webhook.yml
docs/webhook.http

Feature: Try to scrape event in Workflow.

---

.github/workflows/event-scrapper.yml

Fix: Install dependencies for Puppeteer

---

.github/workflows/event-scrapper.yml

- Seems to be a difference in path.

fix: Hardcode the cache path

---

.github/workflows/event-scrapper.yml

fix: Give up on the GitHub Action. Revert back to original setup.

---

cli/scrapers/MeetupParser.ts

Using `new Date()` parses the time into UTC.

Fix: Parses the ISO time string for the start time using Luxon.

---

.github/workflows/nightly-workflow.yml
src/pages/events/index.astro
src/pages/events/search-index.json.ts

The list of events was showing events from 1 day before. Should only upcoming events.

Fix: Ensure we filter out past events.

---

src/content/events/geekshacking/20250830-git-ready-for-action-workshop/index.md

Fixed tags for event. Sorry for the additional pr.

fixed event tags for gh workshop

---

cli/scrapers/EventbriteParser.ts
cli/scrapers/PageScraper.ts

bug: Fix domain and file name.
